# Generated by Django 2.0.6 on 2021-08-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgradu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emisor',
            fields=[
                ('pk_emisor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
                ('comprob', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='mensajero',
            fields=[
                ('ps_mensajero', models.AutoField(primary_key=True, serialize=False)),
                ('id_mensajero', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('pk_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('guia', models.CharField(max_length=9)),
                ('descrip', models.TextField()),
                ('ubication', models.CharField(max_length=80)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tipo', models.TextField()),
                ('fk_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgradu.emisor')),
                ('fk_mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgradu.mensajero')),
            ],
        ),
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('pk_receptor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
                ('guia', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('pk_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=8)),
                ('ubicacion', models.TextField(max_length=80)),
                ('estado', models.TextField(max_length=2)),
                ('fk_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgradu.paquete')),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='paquete',
            name='fk_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgradu.receptor'),
        ),
    ]
