# Generated by Django 2.0.6 on 2021-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgradu', '0002_auto_20210825_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='image',
            field=models.URLField(default='https://imgur.com/a/WFUce60', max_length=800),
        ),
    ]
